//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSWin.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderChanged
    {
        public int OrderChangedOID { get; set; }
        public string OrderID { get; set; }
        public string OrderChangedCategoryCode { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequesterRole { get; set; }
        public string RequesterID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderChangedCategory OrderChangedCategory { get; set; }
    }
}
