//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSWin.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderChangeds = new HashSet<OrderChanged>();
            this.OrderParts = new HashSet<OrderPart>();
        }
    
        public int OrderOID { get; set; }
        public string OrderID { get; set; }
        public string PurchasingOrderID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierAccountID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverTel { get; set; }
        public string ReceiverMobile { get; set; }
        public string ReceiptAddress { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual PurchasingOrder PurchasingOrder { get; set; }
        public virtual SupplierAccount SupplierAccount { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderChanged> OrderChangeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPart> OrderParts { get; set; }
    }
}
