//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSWin.DataSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderChanged> OrderChangeds { get; set; }
        public virtual DbSet<OrderChangedCategory> OrderChangedCategories { get; set; }
        public virtual DbSet<OrderPart> OrderParts { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartUnit> PartUnits { get; set; }
        public virtual DbSet<PurchasingOrder> PurchasingOrders { get; set; }
        public virtual DbSet<SourceList> SourceLists { get; set; }
        public virtual DbSet<SourceOrderList> SourceOrderLists { get; set; }
        public virtual DbSet<SupplierAccount> SupplierAccounts { get; set; }
        public virtual DbSet<SupplierInfo> SupplierInfoes { get; set; }
        public virtual DbSet<SupplierRating> SupplierRatings { get; set; }
        public virtual DbSet<PurchasingOrderDetail> PurchasingOrderDetails { get; set; }
    }
}
