//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSWin.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceOrderList
    {
        public int SourceOrderListOID { get; set; }
        public int OrderPartOID { get; set; }
        public int Batch { get; set; }
        public decimal Discount { get; set; }
        public int Qty { get; set; }
        public Nullable<int> PurchasingOrderDetailListOID { get; set; }
    
        public virtual OrderPart OrderPart { get; set; }
    }
}
