//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSWin.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierAccount()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int SupplierAccountOID { get; set; }
        public string SupplierAccountID { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Tel { get; set; }
        public string SupplierCode { get; set; }
        public string AccountStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatorEmployeeID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SASendLetterState { get; set; }
        public Nullable<System.DateTime> SASendLetterDate { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
    }
}
